package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : linux\generator\src\main\c\\usr\include\bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class accept_physical_link_cp extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte handle() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public accept_physical_link_cp handle(byte handle) {
		this.io.setByteField(this, 0, handle);
		return this;
	}
	@Field(1) 
	public byte key_length() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public accept_physical_link_cp key_length(byte key_length) {
		this.io.setByteField(this, 1, key_length);
		return this;
	}
	@Field(2) 
	public byte key_type() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public accept_physical_link_cp key_type(byte key_type) {
		this.io.setByteField(this, 2, key_type);
		return this;
	}
	/** C type : uint8_t[32] */
	@Array({32}) 
	@Field(3) 
	public Pointer<Byte > key() {
		return this.io.getPointerField(this, 3);
	}
	public accept_physical_link_cp() {
		super();
	}
	public accept_physical_link_cp(Pointer pointer) {
		super(pointer);
	}
}
