package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class add_sco_cp extends Structure<add_sco_cp, add_sco_cp.ByValue, add_sco_cp.ByReference > {
	public short handle;
	public short pkt_type;
	public add_sco_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle", "pkt_type");
	}
	public add_sco_cp(short handle, short pkt_type) {
		super();
		this.handle = handle;
		this.pkt_type = pkt_type;
	}
	public add_sco_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected add_sco_cp newInstance() { return new add_sco_cp(); }
	public static add_sco_cp[] newArray(int arrayLength) {
		return Structure.newArray(add_sco_cp.class, arrayLength);
	}
	public static class ByReference extends add_sco_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends add_sco_cp implements Structure.ByValue {
		
	};
}
