package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\bluetooth.h:78</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class bt_power extends Structure {
	public byte force_active;
	public bt_power() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("force_active");
	}
	public bt_power(byte force_active) {
		super();
		this.force_active = force_active;
	}
	public bt_power(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends bt_power implements Structure.ByReference {
		
	};
	public static class ByValue extends bt_power implements Structure.ByValue {
		
	};
}
