package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * AMP Preferred<br>
 *   Allow use of AMP controllers<br>
 *   If the L2CAP channel is currently on BR/EDR and AMP controller<br>
 *     resources are available, initiate a channel move to AMP.<br>
 *   Channel move requests from the remote device are allowed.<br>
 *   If the L2CAP socket has not been connected yet, try to create<br>
 *     and configure the channel directly on an AMP controller rather<br>
 *     than BR/EDR.<br>
 * <i>native declaration : bluetooth\bluetooth.h:112</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class bt_voice extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short setting() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public bt_voice setting(short setting) {
		this.io.setShortField(this, 0, setting);
		return this;
	}
	public bt_voice() {
		super();
	}
	public bt_voice(Pointer pointer) {
		super(pointer);
	}
}
