package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class cancel_logical_link_cp extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte handle() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public cancel_logical_link_cp handle(byte handle) {
		this.io.setByteField(this, 0, handle);
		return this;
	}
	@Field(1) 
	public byte tx_flow_id() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public cancel_logical_link_cp tx_flow_id(byte tx_flow_id) {
		this.io.setByteField(this, 1, tx_flow_id);
		return this;
	}
	public cancel_logical_link_cp() {
		super();
	}
	public cancel_logical_link_cp(Pointer pointer) {
		super(pointer);
	}
}
