package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class create_conn_cp extends Structure {
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	public short pkt_type;
	public byte pscan_rep_mode;
	public byte pscan_mode;
	public short clock_offset;
	public byte role_switch;
	public create_conn_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bdaddr", "pkt_type", "pscan_rep_mode", "pscan_mode", "clock_offset", "role_switch");
	}
	/** @param bdaddr C type : bdaddr_t */
	public create_conn_cp(bdaddr_t bdaddr, short pkt_type, byte pscan_rep_mode, byte pscan_mode, short clock_offset, byte role_switch) {
		super();
		this.bdaddr = bdaddr;
		this.pkt_type = pkt_type;
		this.pscan_rep_mode = pscan_rep_mode;
		this.pscan_mode = pscan_mode;
		this.clock_offset = clock_offset;
		this.role_switch = role_switch;
	}
	public create_conn_cp(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends create_conn_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends create_conn_cp implements Structure.ByValue {
		
	};
}
