package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class create_logical_link_cp extends Structure<create_logical_link_cp, create_logical_link_cp.ByValue, create_logical_link_cp.ByReference > {
	public byte handle;
	/** C type : uint8_t[16] */
	public byte[] tx_flow = new byte[16];
	/** C type : uint8_t[16] */
	public byte[] rx_flow = new byte[16];
	public create_logical_link_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle", "tx_flow", "rx_flow");
	}
	/**
	 * @param tx_flow C type : uint8_t[16]<br>
	 * @param rx_flow C type : uint8_t[16]
	 */
	public create_logical_link_cp(byte handle, byte tx_flow[], byte rx_flow[]) {
		super();
		this.handle = handle;
		if ((tx_flow.length != this.tx_flow.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.tx_flow = tx_flow;
		if ((rx_flow.length != this.rx_flow.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.rx_flow = rx_flow;
	}
	public create_logical_link_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected create_logical_link_cp newInstance() { return new create_logical_link_cp(); }
	public static create_logical_link_cp[] newArray(int arrayLength) {
		return Structure.newArray(create_logical_link_cp.class, arrayLength);
	}
	public static class ByReference extends create_logical_link_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends create_logical_link_cp implements Structure.ByValue {
		
	};
}
