package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class delete_stored_link_key_cp extends Structure {
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	public byte delete_all;
	public delete_stored_link_key_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bdaddr", "delete_all");
	}
	/** @param bdaddr C type : bdaddr_t */
	public delete_stored_link_key_cp(bdaddr_t bdaddr, byte delete_all) {
		super();
		this.bdaddr = bdaddr;
		this.delete_all = delete_all;
	}
	public delete_stored_link_key_cp(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends delete_stored_link_key_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends delete_stored_link_key_cp implements Structure.ByValue {
		
	};
}
