package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class disconnect_physical_link_cp extends Structure<disconnect_physical_link_cp, disconnect_physical_link_cp.ByValue, disconnect_physical_link_cp.ByReference > {
	public byte handle;
	public byte reason;
	public disconnect_physical_link_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle", "reason");
	}
	public disconnect_physical_link_cp(byte handle, byte reason) {
		super();
		this.handle = handle;
		this.reason = reason;
	}
	public disconnect_physical_link_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected disconnect_physical_link_cp newInstance() { return new disconnect_physical_link_cp(); }
	public static disconnect_physical_link_cp[] newArray(int arrayLength) {
		return Structure.newArray(disconnect_physical_link_cp.class, arrayLength);
	}
	public static class ByReference extends disconnect_physical_link_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends disconnect_physical_link_cp implements Structure.ByValue {
		
	};
}
