package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth/hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class evt_sync_conn_changed extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte status() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public evt_sync_conn_changed status(byte status) {
		this.io.setByteField(this, 0, status);
		return this;
	}
	@Field(1) 
	public short handle() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public evt_sync_conn_changed handle(short handle) {
		this.io.setShortField(this, 1, handle);
		return this;
	}
	@Field(2) 
	public byte trans_interval() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public evt_sync_conn_changed trans_interval(byte trans_interval) {
		this.io.setByteField(this, 2, trans_interval);
		return this;
	}
	@Field(3) 
	public byte retrans_window() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public evt_sync_conn_changed retrans_window(byte retrans_window) {
		this.io.setByteField(this, 3, retrans_window);
		return this;
	}
	@Field(4) 
	public short rx_pkt_len() {
		return this.io.getShortField(this, 4);
	}
	@Field(4) 
	public evt_sync_conn_changed rx_pkt_len(short rx_pkt_len) {
		this.io.setShortField(this, 4, rx_pkt_len);
		return this;
	}
	@Field(5) 
	public short tx_pkt_len() {
		return this.io.getShortField(this, 5);
	}
	@Field(5) 
	public evt_sync_conn_changed tx_pkt_len(short tx_pkt_len) {
		this.io.setShortField(this, 5, tx_pkt_len);
		return this;
	}
	public evt_sync_conn_changed() {
		super();
	}
	public evt_sync_conn_changed(Pointer pointer) {
		super(pointer);
	}
}
