package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class evt_num_completed_blocks extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short total_num_blocks() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public evt_num_completed_blocks total_num_blocks(short total_num_blocks) {
		this.io.setShortField(this, 0, total_num_blocks);
		return this;
	}
	@Field(1) 
	public byte num_handles() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public evt_num_completed_blocks num_handles(byte num_handles) {
		this.io.setByteField(this, 1, num_handles);
		return this;
	}
	/** C type : cmplt_handle[0] */
	@Array({0}) 
	@Field(2) 
	public Pointer<cmplt_handle > handles() {
		return this.io.getPointerField(this, 2);
	}
	public evt_num_completed_blocks() {
		super();
	}
	public evt_num_completed_blocks(Pointer pointer) {
		super(pointer);
	}
}
