package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_cmd_status extends Structure<evt_cmd_status, evt_cmd_status.ByValue, evt_cmd_status.ByReference > {
	public byte status;
	public byte ncmd;
	public short opcode;
	public evt_cmd_status() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "ncmd", "opcode");
	}
	public evt_cmd_status(byte status, byte ncmd, short opcode) {
		super();
		this.status = status;
		this.ncmd = ncmd;
		this.opcode = opcode;
	}
	public evt_cmd_status(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected evt_cmd_status newInstance() { return new evt_cmd_status(); }
	public static evt_cmd_status[] newArray(int arrayLength) {
		return Structure.newArray(evt_cmd_status.class, arrayLength);
	}
	public static class ByReference extends evt_cmd_status implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_cmd_status implements Structure.ByValue {
		
	};
}
