package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_encrypt_change extends Structure<evt_encrypt_change, evt_encrypt_change.ByValue, evt_encrypt_change.ByReference > {
	public byte status;
	public short handle;
	public byte encrypt;
	public evt_encrypt_change() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "handle", "encrypt");
	}
	public evt_encrypt_change(byte status, short handle, byte encrypt) {
		super();
		this.status = status;
		this.handle = handle;
		this.encrypt = encrypt;
	}
	public evt_encrypt_change(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected evt_encrypt_change newInstance() { return new evt_encrypt_change(); }
	public static evt_encrypt_change[] newArray(int arrayLength) {
		return Structure.newArray(evt_encrypt_change.class, arrayLength);
	}
	public static class ByReference extends evt_encrypt_change implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_encrypt_change implements Structure.ByValue {
		
	};
}
