package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_conn_complete extends Structure<evt_conn_complete, evt_conn_complete.ByValue, evt_conn_complete.ByReference > {
	public byte status;
	public short handle;
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	public byte link_type;
	public byte encr_mode;
	public evt_conn_complete() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "handle", "bdaddr", "link_type", "encr_mode");
	}
	/** @param bdaddr C type : bdaddr_t */
	public evt_conn_complete(byte status, short handle, bdaddr_t bdaddr, byte link_type, byte encr_mode) {
		super();
		this.status = status;
		this.handle = handle;
		this.bdaddr = bdaddr;
		this.link_type = link_type;
		this.encr_mode = encr_mode;
	}
	public evt_conn_complete(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected evt_conn_complete newInstance() { return new evt_conn_complete(); }
	public static evt_conn_complete[] newArray(int arrayLength) {
		return Structure.newArray(evt_conn_complete.class, arrayLength);
	}
	public static class ByReference extends evt_conn_complete implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_conn_complete implements Structure.ByValue {
		
	};
}
