package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth/hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class evt_physical_link_loss_warning extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte handle() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public evt_physical_link_loss_warning handle(byte handle) {
		this.io.setByteField(this, 0, handle);
		return this;
	}
	@Field(1) 
	public byte reason() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public evt_physical_link_loss_warning reason(byte reason) {
		this.io.setByteField(this, 1, reason);
		return this;
	}
	public evt_physical_link_loss_warning() {
		super();
	}
	public evt_physical_link_loss_warning(Pointer pointer) {
		super(pointer);
	}
}
