package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_le_meta_event extends Structure {
	public byte subevent;
	/** C type : uint8_t[0] */
	public byte[] data = new byte[0];
	public evt_le_meta_event() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("subevent", "data");
	}
	/** @param data C type : uint8_t[0] */
	public evt_le_meta_event(byte subevent, byte data[]) {
		super();
		this.subevent = subevent;
		if ((data.length != this.data.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.data = data;
	}
	public evt_le_meta_event(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends evt_le_meta_event implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_le_meta_event implements Structure.ByValue {
		
	};
}
