package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_flow_spec_complete extends Structure {
	public byte status;
	public short handle;
	public byte flags;
	public byte direction;
	/** C type : hci_qos */
	public hci_qos qos;
	public evt_flow_spec_complete() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "handle", "flags", "direction", "qos");
	}
	/** @param qos C type : hci_qos */
	public evt_flow_spec_complete(byte status, short handle, byte flags, byte direction, hci_qos qos) {
		super();
		this.status = status;
		this.handle = handle;
		this.flags = flags;
		this.direction = direction;
		this.qos = qos;
	}
	public evt_flow_spec_complete(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends evt_flow_spec_complete implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_flow_spec_complete implements Structure.ByValue {
		
	};
}
