package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_num_completed_blocks extends Structure<evt_num_completed_blocks, evt_num_completed_blocks.ByValue, evt_num_completed_blocks.ByReference > {
	public short total_num_blocks;
	public byte num_handles;
	/** C type : cmplt_handle[0] */
	public cmplt_handle[] handles = new cmplt_handle[0];
	public evt_num_completed_blocks() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("total_num_blocks", "num_handles", "handles");
	}
	/** @param handles C type : cmplt_handle[0] */
	public evt_num_completed_blocks(short total_num_blocks, byte num_handles, cmplt_handle handles[]) {
		super();
		this.total_num_blocks = total_num_blocks;
		this.num_handles = num_handles;
		if ((handles.length != this.handles.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.handles = handles;
	}
	public evt_num_completed_blocks(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected evt_num_completed_blocks newInstance() { return new evt_num_completed_blocks(); }
	public static evt_num_completed_blocks[] newArray(int arrayLength) {
		return Structure.newArray(evt_num_completed_blocks.class, arrayLength);
	}
	public static class ByReference extends evt_num_completed_blocks implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_num_completed_blocks implements Structure.ByValue {
		
	};
}
