package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class evt_le_connection_complete extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte status() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public evt_le_connection_complete status(byte status) {
		this.io.setByteField(this, 0, status);
		return this;
	}
	@Field(1) 
	public short handle() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public evt_le_connection_complete handle(short handle) {
		this.io.setShortField(this, 1, handle);
		return this;
	}
	@Field(2) 
	public byte role() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public evt_le_connection_complete role(byte role) {
		this.io.setByteField(this, 2, role);
		return this;
	}
	@Field(3) 
	public byte peer_bdaddr_type() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public evt_le_connection_complete peer_bdaddr_type(byte peer_bdaddr_type) {
		this.io.setByteField(this, 3, peer_bdaddr_type);
		return this;
	}
	/** C type : bdaddr_t */
	@Field(4) 
	public bdaddr_t peer_bdaddr() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : bdaddr_t */
	@Field(4) 
	public evt_le_connection_complete peer_bdaddr(bdaddr_t peer_bdaddr) {
		this.io.setNativeObjectField(this, 4, peer_bdaddr);
		return this;
	}
	@Field(5) 
	public short interval() {
		return this.io.getShortField(this, 5);
	}
	@Field(5) 
	public evt_le_connection_complete interval(short interval) {
		this.io.setShortField(this, 5, interval);
		return this;
	}
	@Field(6) 
	public short latency() {
		return this.io.getShortField(this, 6);
	}
	@Field(6) 
	public evt_le_connection_complete latency(short latency) {
		this.io.setShortField(this, 6, latency);
		return this;
	}
	@Field(7) 
	public short supervision_timeout() {
		return this.io.getShortField(this, 7);
	}
	@Field(7) 
	public evt_le_connection_complete supervision_timeout(short supervision_timeout) {
		this.io.setShortField(this, 7, supervision_timeout);
		return this;
	}
	@Field(8) 
	public byte master_clock_accuracy() {
		return this.io.getByteField(this, 8);
	}
	@Field(8) 
	public evt_le_connection_complete master_clock_accuracy(byte master_clock_accuracy) {
		this.io.setByteField(this, 8, master_clock_accuracy);
		return this;
	}
	public evt_le_connection_complete() {
		super();
	}
	public evt_le_connection_complete(Pointer pointer) {
		super(pointer);
	}
}
