package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class evt_io_capability_response extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : bdaddr_t */
	@Field(0) 
	public bdaddr_t bdaddr() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : bdaddr_t */
	@Field(0) 
	public evt_io_capability_response bdaddr(bdaddr_t bdaddr) {
		this.io.setNativeObjectField(this, 0, bdaddr);
		return this;
	}
	@Field(1) 
	public byte capability() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public evt_io_capability_response capability(byte capability) {
		this.io.setByteField(this, 1, capability);
		return this;
	}
	@Field(2) 
	public byte oob_data() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public evt_io_capability_response oob_data(byte oob_data) {
		this.io.setByteField(this, 2, oob_data);
		return this;
	}
	@Field(3) 
	public byte authentication() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public evt_io_capability_response authentication(byte authentication) {
		this.io.setByteField(this, 3, authentication);
		return this;
	}
	public evt_io_capability_response() {
		super();
	}
	public evt_io_capability_response(Pointer pointer) {
		super(pointer);
	}
}
