package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_hardware_error extends Structure<evt_hardware_error, evt_hardware_error.ByValue, evt_hardware_error.ByReference > {
	public byte code;
	public evt_hardware_error() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("code");
	}
	public evt_hardware_error(byte code) {
		super();
		this.code = code;
	}
	public evt_hardware_error(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected evt_hardware_error newInstance() { return new evt_hardware_error(); }
	public static evt_hardware_error[] newArray(int arrayLength) {
		return Structure.newArray(evt_hardware_error.class, arrayLength);
	}
	public static class ByReference extends evt_hardware_error implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_hardware_error implements Structure.ByValue {
		
	};
}
