package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class evt_sync_conn_complete extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte status() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public evt_sync_conn_complete status(byte status) {
		this.io.setByteField(this, 0, status);
		return this;
	}
	@Field(1) 
	public short handle() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public evt_sync_conn_complete handle(short handle) {
		this.io.setShortField(this, 1, handle);
		return this;
	}
	/** C type : bdaddr_t */
	@Field(2) 
	public bdaddr_t bdaddr() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : bdaddr_t */
	@Field(2) 
	public evt_sync_conn_complete bdaddr(bdaddr_t bdaddr) {
		this.io.setNativeObjectField(this, 2, bdaddr);
		return this;
	}
	@Field(3) 
	public byte link_type() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public evt_sync_conn_complete link_type(byte link_type) {
		this.io.setByteField(this, 3, link_type);
		return this;
	}
	@Field(4) 
	public byte trans_interval() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public evt_sync_conn_complete trans_interval(byte trans_interval) {
		this.io.setByteField(this, 4, trans_interval);
		return this;
	}
	@Field(5) 
	public byte retrans_window() {
		return this.io.getByteField(this, 5);
	}
	@Field(5) 
	public evt_sync_conn_complete retrans_window(byte retrans_window) {
		this.io.setByteField(this, 5, retrans_window);
		return this;
	}
	@Field(6) 
	public short rx_pkt_len() {
		return this.io.getShortField(this, 6);
	}
	@Field(6) 
	public evt_sync_conn_complete rx_pkt_len(short rx_pkt_len) {
		this.io.setShortField(this, 6, rx_pkt_len);
		return this;
	}
	@Field(7) 
	public short tx_pkt_len() {
		return this.io.getShortField(this, 7);
	}
	@Field(7) 
	public evt_sync_conn_complete tx_pkt_len(short tx_pkt_len) {
		this.io.setShortField(this, 7, tx_pkt_len);
		return this;
	}
	@Field(8) 
	public byte air_mode() {
		return this.io.getByteField(this, 8);
	}
	@Field(8) 
	public evt_sync_conn_complete air_mode(byte air_mode) {
		this.io.setByteField(this, 8, air_mode);
		return this;
	}
	public evt_sync_conn_complete() {
		super();
	}
	public evt_sync_conn_complete(Pointer pointer) {
		super(pointer);
	}
}
