package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_qos_violation extends Structure<evt_qos_violation, evt_qos_violation.ByValue, evt_qos_violation.ByReference > {
	public short handle;
	public evt_qos_violation() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle");
	}
	public evt_qos_violation(short handle) {
		super();
		this.handle = handle;
	}
	public evt_qos_violation(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected evt_qos_violation newInstance() { return new evt_qos_violation(); }
	public static evt_qos_violation[] newArray(int arrayLength) {
		return Structure.newArray(evt_qos_violation.class, arrayLength);
	}
	public static class ByReference extends evt_qos_violation implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_qos_violation implements Structure.ByValue {
		
	};
}
