package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_remote_name_req_complete extends Structure {
	public byte status;
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	/** C type : uint8_t[248] */
	public byte[] name = new byte[248];
	public evt_remote_name_req_complete() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "bdaddr", "name");
	}
	/**
	 * @param bdaddr C type : bdaddr_t<br>
	 * @param name C type : uint8_t[248]
	 */
	public evt_remote_name_req_complete(byte status, bdaddr_t bdaddr, byte name[]) {
		super();
		this.status = status;
		this.bdaddr = bdaddr;
		if ((name.length != this.name.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.name = name;
	}
	public evt_remote_name_req_complete(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends evt_remote_name_req_complete implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_remote_name_req_complete implements Structure.ByValue {
		
	};
}
