package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : linux\generator\src\main\c\\usr\include\bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public abstract class evt_conn_complete extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte status() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public evt_conn_complete status(byte status) {
		this.io.setByteField(this, 0, status);
		return this;
	}
	@Field(1) 
	public short handle() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public evt_conn_complete handle(short handle) {
		this.io.setShortField(this, 1, handle);
		return this;
	}
	/** Conversion Error : bdaddr_t (failed to convert type to Java (undefined type)) */
	@Field(3) 
	public byte link_type() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public evt_conn_complete link_type(byte link_type) {
		this.io.setByteField(this, 3, link_type);
		return this;
	}
	@Field(4) 
	public byte encr_mode() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public evt_conn_complete encr_mode(byte encr_mode) {
		this.io.setByteField(this, 4, encr_mode);
		return this;
	}
}
