package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class evt_simple_pairing_complete extends Structure<evt_simple_pairing_complete, evt_simple_pairing_complete.ByValue, evt_simple_pairing_complete.ByReference > {
	public byte status;
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	public evt_simple_pairing_complete() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "bdaddr");
	}
	/** @param bdaddr C type : bdaddr_t */
	public evt_simple_pairing_complete(byte status, bdaddr_t bdaddr) {
		super();
		this.status = status;
		this.bdaddr = bdaddr;
	}
	public evt_simple_pairing_complete(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected evt_simple_pairing_complete newInstance() { return new evt_simple_pairing_complete(); }
	public static evt_simple_pairing_complete[] newArray(int arrayLength) {
		return Structure.newArray(evt_simple_pairing_complete.class, arrayLength);
	}
	public static class ByReference extends evt_simple_pairing_complete implements Structure.ByReference {
		
	};
	public static class ByValue extends evt_simple_pairing_complete implements Structure.ByValue {
		
	};
}
