package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class exit_park_mode_cp extends Structure<exit_park_mode_cp, exit_park_mode_cp.ByValue, exit_park_mode_cp.ByReference > {
	public short handle;
	public exit_park_mode_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle");
	}
	public exit_park_mode_cp(short handle) {
		super();
		this.handle = handle;
	}
	public exit_park_mode_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected exit_park_mode_cp newInstance() { return new exit_park_mode_cp(); }
	public static exit_park_mode_cp[] newArray(int arrayLength) {
		return Structure.newArray(exit_park_mode_cp.class, arrayLength);
	}
	public static class ByReference extends exit_park_mode_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends exit_park_mode_cp implements Structure.ByValue {
		
	};
}
