package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h:2345</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class hci_dev_req extends Structure {
	public short dev_id;
	public int dev_opt;
	public hci_dev_req() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("dev_id", "dev_opt");
	}
	public hci_dev_req(short dev_id, int dev_opt) {
		super();
		this.dev_id = dev_id;
		this.dev_opt = dev_opt;
	}
	public hci_dev_req(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends hci_dev_req implements Structure.ByReference {
		
	};
	public static class ByValue extends hci_dev_req implements Structure.ByValue {
		
	};
}
