package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h:2350</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class hci_dev_list_req extends Structure {
	public short dev_num;
	/**
	 * hci_dev_req structures<br>
	 * C type : hci_dev_req[0]
	 */
	public hci_dev_req[] dev_req = new hci_dev_req[0];
	public hci_dev_list_req() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("dev_num", "dev_req");
	}
	/**
	 * @param dev_req hci_dev_req structures<br>
	 * C type : hci_dev_req[0]
	 */
	public hci_dev_list_req(short dev_num, hci_dev_req dev_req[]) {
		super();
		this.dev_num = dev_num;
		if ((dev_req.length != this.dev_req.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.dev_req = dev_req;
	}
	public hci_dev_list_req(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends hci_dev_list_req implements Structure.ByReference {
		
	};
	public static class ByValue extends hci_dev_list_req implements Structure.ByValue {
		
	};
}
