package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class hci_command_hdr extends Structure<hci_command_hdr, hci_command_hdr.ByValue, hci_command_hdr.ByReference > {
	/** OCF & OGF */
	public short opcode;
	public byte plen;
	public hci_command_hdr() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("opcode", "plen");
	}
	/** @param opcode OCF & OGF */
	public hci_command_hdr(short opcode, byte plen) {
		super();
		this.opcode = opcode;
		this.plen = plen;
	}
	public hci_command_hdr(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected hci_command_hdr newInstance() { return new hci_command_hdr(); }
	public static hci_command_hdr[] newArray(int arrayLength) {
		return Structure.newArray(hci_command_hdr.class, arrayLength);
	}
	public static class ByReference extends hci_command_hdr implements Structure.ByReference {
		
	};
	public static class ByValue extends hci_command_hdr implements Structure.ByValue {
		
	};
}
