package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth\hci.h:2313</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class hci_dev_info extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short dev_id() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public hci_dev_info dev_id(short dev_id) {
		this.io.setShortField(this, 0, dev_id);
		return this;
	}
	/** C type : char[8] */
	@Array({8}) 
	@Field(1) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : bdaddr_t */
	@Field(2) 
	public bdaddr_t bdaddr() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : bdaddr_t */
	@Field(2) 
	public hci_dev_info bdaddr(bdaddr_t bdaddr) {
		this.io.setNativeObjectField(this, 2, bdaddr);
		return this;
	}
	@Field(3) 
	public int flags() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public hci_dev_info flags(int flags) {
		this.io.setIntField(this, 3, flags);
		return this;
	}
	@Field(4) 
	public byte type() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public hci_dev_info type(byte type) {
		this.io.setByteField(this, 4, type);
		return this;
	}
	/** C type : uint8_t[8] */
	@Array({8}) 
	@Field(5) 
	public Pointer<Byte > features() {
		return this.io.getPointerField(this, 5);
	}
	@Field(6) 
	public int pkt_type() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public hci_dev_info pkt_type(int pkt_type) {
		this.io.setIntField(this, 6, pkt_type);
		return this;
	}
	@Field(7) 
	public int link_policy() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public hci_dev_info link_policy(int link_policy) {
		this.io.setIntField(this, 7, link_policy);
		return this;
	}
	@Field(8) 
	public int link_mode() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public hci_dev_info link_mode(int link_mode) {
		this.io.setIntField(this, 8, link_mode);
		return this;
	}
	@Field(9) 
	public short acl_mtu() {
		return this.io.getShortField(this, 9);
	}
	@Field(9) 
	public hci_dev_info acl_mtu(short acl_mtu) {
		this.io.setShortField(this, 9, acl_mtu);
		return this;
	}
	@Field(10) 
	public short acl_pkts() {
		return this.io.getShortField(this, 10);
	}
	@Field(10) 
	public hci_dev_info acl_pkts(short acl_pkts) {
		this.io.setShortField(this, 10, acl_pkts);
		return this;
	}
	@Field(11) 
	public short sco_mtu() {
		return this.io.getShortField(this, 11);
	}
	@Field(11) 
	public hci_dev_info sco_mtu(short sco_mtu) {
		this.io.setShortField(this, 11, sco_mtu);
		return this;
	}
	@Field(12) 
	public short sco_pkts() {
		return this.io.getShortField(this, 12);
	}
	@Field(12) 
	public hci_dev_info sco_pkts(short sco_pkts) {
		this.io.setShortField(this, 12, sco_pkts);
		return this;
	}
	/** C type : hci_dev_stats */
	@Field(13) 
	public hci_dev_stats stat() {
		return this.io.getNativeObjectField(this, 13);
	}
	/** C type : hci_dev_stats */
	@Field(13) 
	public hci_dev_info stat(hci_dev_stats stat) {
		this.io.setNativeObjectField(this, 13, stat);
		return this;
	}
	public hci_dev_info() {
		super();
	}
	public hci_dev_info(Pointer pointer) {
		super(pointer);
	}
}
