package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth/hci.h:2380</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class hci_dev_req extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short dev_id() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public hci_dev_req dev_id(short dev_id) {
		this.io.setShortField(this, 0, dev_id);
		return this;
	}
	@Field(1) 
	public int dev_opt() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public hci_dev_req dev_opt(int dev_opt) {
		this.io.setIntField(this, 1, dev_opt);
		return this;
	}
	public hci_dev_req() {
		super();
	}
	public hci_dev_req(Pointer pointer) {
		super(pointer);
	}
}
