package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class hci_event_hdr extends Structure {
	public byte evt;
	public byte plen;
	public hci_event_hdr() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("evt", "plen");
	}
	public hci_event_hdr(byte evt, byte plen) {
		super();
		this.evt = evt;
		this.plen = plen;
	}
	public hci_event_hdr(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends hci_event_hdr implements Structure.ByReference {
		
	};
	public static class ByValue extends hci_event_hdr implements Structure.ByValue {
		
	};
}
