package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : linux\generator\src\main\c\\usr\include\bluetooth\hci.h:2366</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public abstract class hci_conn_info extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short handle() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public hci_conn_info handle(short handle) {
		this.io.setShortField(this, 0, handle);
		return this;
	}
	/** Conversion Error : bdaddr_t (failed to convert type to Java (undefined type)) */
	@Field(2) 
	public byte type() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public hci_conn_info type(byte type) {
		this.io.setByteField(this, 2, type);
		return this;
	}
	@Field(3) 
	public byte out() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public hci_conn_info out(byte out) {
		this.io.setByteField(this, 3, out);
		return this;
	}
	@Field(4) 
	public short state() {
		return this.io.getShortField(this, 4);
	}
	@Field(4) 
	public hci_conn_info state(short state) {
		this.io.setShortField(this, 4, state);
		return this;
	}
	@Field(5) 
	public int link_mode() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public hci_conn_info link_mode(int link_mode) {
		this.io.setIntField(this, 5, link_mode);
		return this;
	}
}
