package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class host_buffer_size_cp extends Structure {
	public short acl_mtu;
	public byte sco_mtu;
	public short acl_max_pkt;
	public short sco_max_pkt;
	public host_buffer_size_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("acl_mtu", "sco_mtu", "acl_max_pkt", "sco_max_pkt");
	}
	public host_buffer_size_cp(short acl_mtu, byte sco_mtu, short acl_max_pkt, short sco_max_pkt) {
		super();
		this.acl_mtu = acl_mtu;
		this.sco_mtu = sco_mtu;
		this.acl_max_pkt = acl_max_pkt;
		this.sco_max_pkt = sco_max_pkt;
	}
	public host_buffer_size_cp(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends host_buffer_size_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends host_buffer_size_cp implements Structure.ByValue {
		
	};
}
