package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : linux\generator\src\main\c\\usr\include\bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public abstract class inquiry_info_with_rssi extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : bdaddr_t (failed to convert type to Java (undefined type)) */
	@Field(1) 
	public byte pscan_rep_mode() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public inquiry_info_with_rssi pscan_rep_mode(byte pscan_rep_mode) {
		this.io.setByteField(this, 1, pscan_rep_mode);
		return this;
	}
	@Field(2) 
	public byte pscan_period_mode() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public inquiry_info_with_rssi pscan_period_mode(byte pscan_period_mode) {
		this.io.setByteField(this, 2, pscan_period_mode);
		return this;
	}
	/** C type : uint8_t[3] */
	@Array({3}) 
	@Field(3) 
	public Pointer<Byte > dev_class() {
		return this.io.getPointerField(this, 3);
	}
	@Field(4) 
	public short clock_offset() {
		return this.io.getShortField(this, 4);
	}
	@Field(4) 
	public inquiry_info_with_rssi clock_offset(short clock_offset) {
		this.io.setShortField(this, 4, clock_offset);
		return this;
	}
	@Field(5) 
	public byte rssi() {
		return this.io.getByteField(this, 5);
	}
	@Field(5) 
	public inquiry_info_with_rssi rssi(byte rssi) {
		this.io.setByteField(this, 5, rssi);
		return this;
	}
}
