package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class inquiry_cp extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : uint8_t[3] */
	@Array({3}) 
	@Field(0) 
	public Pointer<Byte > lap() {
		return this.io.getPointerField(this, 0);
	}
	/** 1.28s units */
	@Field(1) 
	public byte length() {
		return this.io.getByteField(this, 1);
	}
	/** 1.28s units */
	@Field(1) 
	public inquiry_cp length(byte length) {
		this.io.setByteField(this, 1, length);
		return this;
	}
	@Field(2) 
	public byte num_rsp() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public inquiry_cp num_rsp(byte num_rsp) {
		this.io.setByteField(this, 2, num_rsp);
		return this;
	}
	public inquiry_cp() {
		super();
	}
	public inquiry_cp(Pointer pointer) {
		super(pointer);
	}
}
