package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class le_advertising_info extends Structure<le_advertising_info, le_advertising_info.ByValue, le_advertising_info.ByReference > {
	public byte evt_type;
	public byte bdaddr_type;
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	public byte length;
	/** C type : uint8_t[0] */
	public byte[] data = new byte[0];
	public le_advertising_info() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("evt_type", "bdaddr_type", "bdaddr", "length", "data");
	}
	/**
	 * @param bdaddr C type : bdaddr_t<br>
	 * @param data C type : uint8_t[0]
	 */
	public le_advertising_info(byte evt_type, byte bdaddr_type, bdaddr_t bdaddr, byte length, byte data[]) {
		super();
		this.evt_type = evt_type;
		this.bdaddr_type = bdaddr_type;
		this.bdaddr = bdaddr;
		this.length = length;
		if ((data.length != this.data.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.data = data;
	}
	public le_advertising_info(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected le_advertising_info newInstance() { return new le_advertising_info(); }
	public static le_advertising_info[] newArray(int arrayLength) {
		return Structure.newArray(le_advertising_info.class, arrayLength);
	}
	public static class ByReference extends le_advertising_info implements Structure.ByReference {
		
	};
	public static class ByValue extends le_advertising_info implements Structure.ByValue {
		
	};
}
