package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class le_rand_rp extends Structure<le_rand_rp, le_rand_rp.ByValue, le_rand_rp.ByReference > {
	public byte status;
	public long random;
	public le_rand_rp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "random");
	}
	public le_rand_rp(byte status, long random) {
		super();
		this.status = status;
		this.random = random;
	}
	public le_rand_rp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected le_rand_rp newInstance() { return new le_rand_rp(); }
	public static le_rand_rp[] newArray(int arrayLength) {
		return Structure.newArray(le_rand_rp.class, arrayLength);
	}
	public static class ByReference extends le_rand_rp implements Structure.ByReference {
		
	};
	public static class ByValue extends le_rand_rp implements Structure.ByValue {
		
	};
}
