package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class le_set_scan_parameters_cp extends Structure<le_set_scan_parameters_cp, le_set_scan_parameters_cp.ByValue, le_set_scan_parameters_cp.ByReference > {
	public byte type;
	public short interval;
	public short window;
	public byte own_bdaddr_type;
	public byte filter;
	public le_set_scan_parameters_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("type", "interval", "window", "own_bdaddr_type", "filter");
	}
	public le_set_scan_parameters_cp(byte type, short interval, short window, byte own_bdaddr_type, byte filter) {
		super();
		this.type = type;
		this.interval = interval;
		this.window = window;
		this.own_bdaddr_type = own_bdaddr_type;
		this.filter = filter;
	}
	public le_set_scan_parameters_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected le_set_scan_parameters_cp newInstance() { return new le_set_scan_parameters_cp(); }
	public static le_set_scan_parameters_cp[] newArray(int arrayLength) {
		return Structure.newArray(le_set_scan_parameters_cp.class, arrayLength);
	}
	public static class ByReference extends le_set_scan_parameters_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends le_set_scan_parameters_cp implements Structure.ByValue {
		
	};
}
