package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class le_start_encryption_cp extends Structure {
	public short handle;
	public long random;
	public short diversifier;
	/** C type : uint8_t[16] */
	public byte[] key = new byte[16];
	public le_start_encryption_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle", "random", "diversifier", "key");
	}
	/** @param key C type : uint8_t[16] */
	public le_start_encryption_cp(short handle, long random, short diversifier, byte key[]) {
		super();
		this.handle = handle;
		this.random = random;
		this.diversifier = diversifier;
		if ((key.length != this.key.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.key = key;
	}
	public le_start_encryption_cp(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends le_start_encryption_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends le_start_encryption_cp implements Structure.ByValue {
		
	};
}
