package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class le_set_random_address_cp extends Structure<le_set_random_address_cp, le_set_random_address_cp.ByValue, le_set_random_address_cp.ByReference > {
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	public le_set_random_address_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bdaddr");
	}
	/** @param bdaddr C type : bdaddr_t */
	public le_set_random_address_cp(bdaddr_t bdaddr) {
		super();
		this.bdaddr = bdaddr;
	}
	public le_set_random_address_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected le_set_random_address_cp newInstance() { return new le_set_random_address_cp(); }
	public static le_set_random_address_cp[] newArray(int arrayLength) {
		return Structure.newArray(le_set_random_address_cp.class, arrayLength);
	}
	public static class ByReference extends le_set_random_address_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends le_set_random_address_cp implements Structure.ByValue {
		
	};
}
