package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : linux\generator\src\main\c\\usr\include\bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class le_set_scan_parameters_cp extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte type() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public le_set_scan_parameters_cp type(byte type) {
		this.io.setByteField(this, 0, type);
		return this;
	}
	@Field(1) 
	public short interval() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public le_set_scan_parameters_cp interval(short interval) {
		this.io.setShortField(this, 1, interval);
		return this;
	}
	@Field(2) 
	public short window() {
		return this.io.getShortField(this, 2);
	}
	@Field(2) 
	public le_set_scan_parameters_cp window(short window) {
		this.io.setShortField(this, 2, window);
		return this;
	}
	@Field(3) 
	public byte own_bdaddr_type() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public le_set_scan_parameters_cp own_bdaddr_type(byte own_bdaddr_type) {
		this.io.setByteField(this, 3, own_bdaddr_type);
		return this;
	}
	@Field(4) 
	public byte filter() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public le_set_scan_parameters_cp filter(byte filter) {
		this.io.setByteField(this, 4, filter);
		return this;
	}
	public le_set_scan_parameters_cp() {
		super();
	}
	public le_set_scan_parameters_cp(Pointer pointer) {
		super(pointer);
	}
}
