package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class link_key_reply_cp extends Structure<link_key_reply_cp, link_key_reply_cp.ByValue, link_key_reply_cp.ByReference > {
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	/** C type : uint8_t[16] */
	public byte[] link_key = new byte[16];
	public link_key_reply_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bdaddr", "link_key");
	}
	/**
	 * @param bdaddr C type : bdaddr_t<br>
	 * @param link_key C type : uint8_t[16]
	 */
	public link_key_reply_cp(bdaddr_t bdaddr, byte link_key[]) {
		super();
		this.bdaddr = bdaddr;
		if ((link_key.length != this.link_key.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.link_key = link_key;
	}
	public link_key_reply_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected link_key_reply_cp newInstance() { return new link_key_reply_cp(); }
	public static link_key_reply_cp[] newArray(int arrayLength) {
		return Structure.newArray(link_key_reply_cp.class, arrayLength);
	}
	public static class ByReference extends link_key_reply_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends link_key_reply_cp implements Structure.ByValue {
		
	};
}
