package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bluetooth/hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class periodic_inquiry_cp extends StructObject {
	static {
		BridJ.register();
	}
	/** 1.28s units */
	@Field(0) 
	public short max_period() {
		return this.io.getShortField(this, 0);
	}
	/** 1.28s units */
	@Field(0) 
	public periodic_inquiry_cp max_period(short max_period) {
		this.io.setShortField(this, 0, max_period);
		return this;
	}
	/** 1.28s units */
	@Field(1) 
	public short min_period() {
		return this.io.getShortField(this, 1);
	}
	/** 1.28s units */
	@Field(1) 
	public periodic_inquiry_cp min_period(short min_period) {
		this.io.setShortField(this, 1, min_period);
		return this;
	}
	/** C type : uint8_t[3] */
	@Array({3}) 
	@Field(2) 
	public Pointer<Byte > lap() {
		return this.io.getPointerField(this, 2);
	}
	/** 1.28s units */
	@Field(3) 
	public byte length() {
		return this.io.getByteField(this, 3);
	}
	/** 1.28s units */
	@Field(3) 
	public periodic_inquiry_cp length(byte length) {
		this.io.setByteField(this, 3, length);
		return this;
	}
	@Field(4) 
	public byte num_rsp() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public periodic_inquiry_cp num_rsp(byte num_rsp) {
		this.io.setByteField(this, 4, num_rsp);
		return this;
	}
	public periodic_inquiry_cp() {
		super();
	}
	public periodic_inquiry_cp(Pointer pointer) {
		super(pointer);
	}
}
