package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : linux\generator\src\main\c\\usr\include\bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class qos_setup_cp extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short handle() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public qos_setup_cp handle(short handle) {
		this.io.setShortField(this, 0, handle);
		return this;
	}
	/** Reserved */
	@Field(1) 
	public byte flags() {
		return this.io.getByteField(this, 1);
	}
	/** Reserved */
	@Field(1) 
	public qos_setup_cp flags(byte flags) {
		this.io.setByteField(this, 1, flags);
		return this;
	}
	/** C type : hci_qos */
	@Field(2) 
	public hci_qos qos() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : hci_qos */
	@Field(2) 
	public qos_setup_cp qos(hci_qos qos) {
		this.io.setNativeObjectField(this, 2, qos);
		return this;
	}
	public qos_setup_cp() {
		super();
	}
	public qos_setup_cp(Pointer pointer) {
		super(pointer);
	}
}
