package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class read_rssi_rp extends Structure<read_rssi_rp, read_rssi_rp.ByValue, read_rssi_rp.ByReference > {
	public byte status;
	public short handle;
	public byte rssi;
	public read_rssi_rp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "handle", "rssi");
	}
	public read_rssi_rp(byte status, short handle, byte rssi) {
		super();
		this.status = status;
		this.handle = handle;
		this.rssi = rssi;
	}
	public read_rssi_rp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected read_rssi_rp newInstance() { return new read_rssi_rp(); }
	public static read_rssi_rp[] newArray(int arrayLength) {
		return Structure.newArray(read_rssi_rp.class, arrayLength);
	}
	public static class ByReference extends read_rssi_rp implements Structure.ByReference {
		
	};
	public static class ByValue extends read_rssi_rp implements Structure.ByValue {
		
	};
}
