package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class read_link_quality_rp extends Structure<read_link_quality_rp, read_link_quality_rp.ByValue, read_link_quality_rp.ByReference > {
	public byte status;
	public short handle;
	public byte link_quality;
	public read_link_quality_rp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "handle", "link_quality");
	}
	public read_link_quality_rp(byte status, short handle, byte link_quality) {
		super();
		this.status = status;
		this.handle = handle;
		this.link_quality = link_quality;
	}
	public read_link_quality_rp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected read_link_quality_rp newInstance() { return new read_link_quality_rp(); }
	public static read_link_quality_rp[] newArray(int arrayLength) {
		return Structure.newArray(read_link_quality_rp.class, arrayLength);
	}
	public static class ByReference extends read_link_quality_rp implements Structure.ByReference {
		
	};
	public static class ByValue extends read_link_quality_rp implements Structure.ByValue {
		
	};
}
