package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class read_local_oob_data_rp extends Structure {
	public byte status;
	/** C type : uint8_t[16] */
	public byte[] hash = new byte[16];
	/** C type : uint8_t[16] */
	public byte[] randomizer = new byte[16];
	public read_local_oob_data_rp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "hash", "randomizer");
	}
	/**
	 * @param hash C type : uint8_t[16]<br>
	 * @param randomizer C type : uint8_t[16]
	 */
	public read_local_oob_data_rp(byte status, byte hash[], byte randomizer[]) {
		super();
		this.status = status;
		if ((hash.length != this.hash.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.hash = hash;
		if ((randomizer.length != this.randomizer.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.randomizer = randomizer;
	}
	public read_local_oob_data_rp(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends read_local_oob_data_rp implements Structure.ByReference {
		
	};
	public static class ByValue extends read_local_oob_data_rp implements Structure.ByValue {
		
	};
}
