package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class read_le_host_supported_rp extends Structure<read_le_host_supported_rp, read_le_host_supported_rp.ByValue, read_le_host_supported_rp.ByReference > {
	public byte status;
	public byte le;
	public byte simul;
	public read_le_host_supported_rp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "le", "simul");
	}
	public read_le_host_supported_rp(byte status, byte le, byte simul) {
		super();
		this.status = status;
		this.le = le;
		this.simul = simul;
	}
	public read_le_host_supported_rp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected read_le_host_supported_rp newInstance() { return new read_le_host_supported_rp(); }
	public static read_le_host_supported_rp[] newArray(int arrayLength) {
		return Structure.newArray(read_le_host_supported_rp.class, arrayLength);
	}
	public static class ByReference extends read_le_host_supported_rp implements Structure.ByReference {
		
	};
	public static class ByValue extends read_le_host_supported_rp implements Structure.ByValue {
		
	};
}
