package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class read_stored_link_key_cp extends Structure<read_stored_link_key_cp, read_stored_link_key_cp.ByValue, read_stored_link_key_cp.ByReference > {
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	public byte read_all;
	public read_stored_link_key_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bdaddr", "read_all");
	}
	/** @param bdaddr C type : bdaddr_t */
	public read_stored_link_key_cp(bdaddr_t bdaddr, byte read_all) {
		super();
		this.bdaddr = bdaddr;
		this.read_all = read_all;
	}
	public read_stored_link_key_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected read_stored_link_key_cp newInstance() { return new read_stored_link_key_cp(); }
	public static read_stored_link_key_cp[] newArray(int arrayLength) {
		return Structure.newArray(read_stored_link_key_cp.class, arrayLength);
	}
	public static class ByReference extends read_stored_link_key_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends read_stored_link_key_cp implements Structure.ByValue {
		
	};
}
