package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class read_data_block_size_rp extends Structure {
	public byte status;
	public short max_acl_len;
	public short data_block_len;
	public short num_blocks;
	public read_data_block_size_rp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "max_acl_len", "data_block_len", "num_blocks");
	}
	public read_data_block_size_rp(byte status, short max_acl_len, short data_block_len, short num_blocks) {
		super();
		this.status = status;
		this.max_acl_len = max_acl_len;
		this.data_block_len = data_block_len;
		this.num_blocks = num_blocks;
	}
	public read_data_block_size_rp(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends read_data_block_size_rp implements Structure.ByReference {
		
	};
	public static class ByValue extends read_data_block_size_rp implements Structure.ByValue {
		
	};
}
