package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class read_local_amp_info_rp extends Structure<read_local_amp_info_rp, read_local_amp_info_rp.ByValue, read_local_amp_info_rp.ByReference > {
	public byte status;
	public byte amp_status;
	public int total_bandwidth;
	public int max_guaranteed_bandwidth;
	public int min_latency;
	public int max_pdu_size;
	public byte controller_type;
	public short pal_caps;
	public short max_amp_assoc_length;
	public int max_flush_timeout;
	public int best_effort_flush_timeout;
	public read_local_amp_info_rp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "amp_status", "total_bandwidth", "max_guaranteed_bandwidth", "min_latency", "max_pdu_size", "controller_type", "pal_caps", "max_amp_assoc_length", "max_flush_timeout", "best_effort_flush_timeout");
	}
	public read_local_amp_info_rp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected read_local_amp_info_rp newInstance() { return new read_local_amp_info_rp(); }
	public static read_local_amp_info_rp[] newArray(int arrayLength) {
		return Structure.newArray(read_local_amp_info_rp.class, arrayLength);
	}
	public static class ByReference extends read_local_amp_info_rp implements Structure.ByReference {
		
	};
	public static class ByValue extends read_local_amp_info_rp implements Structure.ByValue {
		
	};
}
