package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class read_afh_map_rp extends Structure<read_afh_map_rp, read_afh_map_rp.ByValue, read_afh_map_rp.ByReference > {
	public byte status;
	public short handle;
	public byte mode;
	/** C type : uint8_t[10] */
	public byte[] map = new byte[10];
	public read_afh_map_rp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "handle", "mode", "map");
	}
	/** @param map C type : uint8_t[10] */
	public read_afh_map_rp(byte status, short handle, byte mode, byte map[]) {
		super();
		this.status = status;
		this.handle = handle;
		this.mode = mode;
		if ((map.length != this.map.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.map = map;
	}
	public read_afh_map_rp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected read_afh_map_rp newInstance() { return new read_afh_map_rp(); }
	public static read_afh_map_rp[] newArray(int arrayLength) {
		return Structure.newArray(read_afh_map_rp.class, arrayLength);
	}
	public static class ByReference extends read_afh_map_rp implements Structure.ByReference {
		
	};
	public static class ByValue extends read_afh_map_rp implements Structure.ByValue {
		
	};
}
