package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class read_buffer_size_rp extends Structure<read_buffer_size_rp, read_buffer_size_rp.ByValue, read_buffer_size_rp.ByReference > {
	public byte status;
	public short acl_mtu;
	public byte sco_mtu;
	public short acl_max_pkt;
	public short sco_max_pkt;
	public read_buffer_size_rp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("status", "acl_mtu", "sco_mtu", "acl_max_pkt", "sco_max_pkt");
	}
	public read_buffer_size_rp(byte status, short acl_mtu, byte sco_mtu, short acl_max_pkt, short sco_max_pkt) {
		super();
		this.status = status;
		this.acl_mtu = acl_mtu;
		this.sco_mtu = sco_mtu;
		this.acl_max_pkt = acl_max_pkt;
		this.sco_max_pkt = sco_max_pkt;
	}
	public read_buffer_size_rp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected read_buffer_size_rp newInstance() { return new read_buffer_size_rp(); }
	public static read_buffer_size_rp[] newArray(int arrayLength) {
		return Structure.newArray(read_buffer_size_rp.class, arrayLength);
	}
	public static class ByReference extends read_buffer_size_rp implements Structure.ByReference {
		
	};
	public static class ByValue extends read_buffer_size_rp implements Structure.ByValue {
		
	};
}
