package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sniff_mode_cp extends Structure<sniff_mode_cp, sniff_mode_cp.ByValue, sniff_mode_cp.ByReference > {
	public short handle;
	public short max_interval;
	public short min_interval;
	public short attempt;
	public short timeout;
	public sniff_mode_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle", "max_interval", "min_interval", "attempt", "timeout");
	}
	public sniff_mode_cp(short handle, short max_interval, short min_interval, short attempt, short timeout) {
		super();
		this.handle = handle;
		this.max_interval = max_interval;
		this.min_interval = min_interval;
		this.attempt = attempt;
		this.timeout = timeout;
	}
	public sniff_mode_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected sniff_mode_cp newInstance() { return new sniff_mode_cp(); }
	public static sniff_mode_cp[] newArray(int arrayLength) {
		return Structure.newArray(sniff_mode_cp.class, arrayLength);
	}
	public static class ByReference extends sniff_mode_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends sniff_mode_cp implements Structure.ByValue {
		
	};
}
