package voice.linux.jna.bluetooth;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * HCI CMSG flags<br>
 * <i>native declaration : bluetooth/hci.h:2310</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("bluetooth") 
public class sockaddr_hci extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : sa_family_t */
	@Field(0) 
	public short hci_family() {
		return this.io.getShortField(this, 0);
	}
	/** C type : sa_family_t */
	@Field(0) 
	public sockaddr_hci hci_family(short hci_family) {
		this.io.setShortField(this, 0, hci_family);
		return this;
	}
	@Field(1) 
	public short hci_dev() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public sockaddr_hci hci_dev(short hci_dev) {
		this.io.setShortField(this, 1, hci_dev);
		return this;
	}
	@Field(2) 
	public short hci_channel() {
		return this.io.getShortField(this, 2);
	}
	@Field(2) 
	public sockaddr_hci hci_channel(short hci_channel) {
		this.io.setShortField(this, 2, hci_channel);
		return this;
	}
	public sockaddr_hci() {
		super();
	}
	public sockaddr_hci(Pointer pointer) {
		super(pointer);
	}
}
