package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class switch_role_cp extends Structure<switch_role_cp, switch_role_cp.ByValue, switch_role_cp.ByReference > {
	/** C type : bdaddr_t */
	public bdaddr_t bdaddr;
	public byte role;
	public switch_role_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bdaddr", "role");
	}
	/** @param bdaddr C type : bdaddr_t */
	public switch_role_cp(bdaddr_t bdaddr, byte role) {
		super();
		this.bdaddr = bdaddr;
		this.role = role;
	}
	public switch_role_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected switch_role_cp newInstance() { return new switch_role_cp(); }
	public static switch_role_cp[] newArray(int arrayLength) {
		return Structure.newArray(switch_role_cp.class, arrayLength);
	}
	public static class ByReference extends switch_role_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends switch_role_cp implements Structure.ByValue {
		
	};
}
