package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class write_le_host_supported_cp extends Structure<write_le_host_supported_cp, write_le_host_supported_cp.ByValue, write_le_host_supported_cp.ByReference > {
	public byte le;
	public byte simul;
	public write_le_host_supported_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("le", "simul");
	}
	public write_le_host_supported_cp(byte le, byte simul) {
		super();
		this.le = le;
		this.simul = simul;
	}
	public write_le_host_supported_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected write_le_host_supported_cp newInstance() { return new write_le_host_supported_cp(); }
	public static write_le_host_supported_cp[] newArray(int arrayLength) {
		return Structure.newArray(write_le_host_supported_cp.class, arrayLength);
	}
	public static class ByReference extends write_le_host_supported_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends write_le_host_supported_cp implements Structure.ByValue {
		
	};
}
