package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class write_inquiry_transmit_power_level_cp extends Structure<write_inquiry_transmit_power_level_cp, write_inquiry_transmit_power_level_cp.ByValue, write_inquiry_transmit_power_level_cp.ByReference > {
	public byte level;
	public write_inquiry_transmit_power_level_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("level");
	}
	public write_inquiry_transmit_power_level_cp(byte level) {
		super();
		this.level = level;
	}
	public write_inquiry_transmit_power_level_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected write_inquiry_transmit_power_level_cp newInstance() { return new write_inquiry_transmit_power_level_cp(); }
	public static write_inquiry_transmit_power_level_cp[] newArray(int arrayLength) {
		return Structure.newArray(write_inquiry_transmit_power_level_cp.class, arrayLength);
	}
	public static class ByReference extends write_inquiry_transmit_power_level_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends write_inquiry_transmit_power_level_cp implements Structure.ByValue {
		
	};
}
