package voice.linux.jna.bluetooth;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class write_class_of_dev_cp extends Structure {
	/** C type : uint8_t[3] */
	public byte[] dev_class = new byte[3];
	public write_class_of_dev_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("dev_class");
	}
	/** @param dev_class C type : uint8_t[3] */
	public write_class_of_dev_cp(byte dev_class[]) {
		super();
		if ((dev_class.length != this.dev_class.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.dev_class = dev_class;
	}
	public write_class_of_dev_cp(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends write_class_of_dev_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends write_class_of_dev_cp implements Structure.ByValue {
		
	};
}
