package voice.linux.jna.bluetooth;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : bluetooth\hci.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class write_link_supervision_timeout_cp extends Structure<write_link_supervision_timeout_cp, write_link_supervision_timeout_cp.ByValue, write_link_supervision_timeout_cp.ByReference > {
	public short handle;
	public short timeout;
	public write_link_supervision_timeout_cp() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("handle", "timeout");
	}
	public write_link_supervision_timeout_cp(short handle, short timeout) {
		super();
		this.handle = handle;
		this.timeout = timeout;
	}
	public write_link_supervision_timeout_cp(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected write_link_supervision_timeout_cp newInstance() { return new write_link_supervision_timeout_cp(); }
	public static write_link_supervision_timeout_cp[] newArray(int arrayLength) {
		return Structure.newArray(write_link_supervision_timeout_cp.class, arrayLength);
	}
	public static class ByReference extends write_link_supervision_timeout_cp implements Structure.ByReference {
		
	};
	public static class ByValue extends write_link_supervision_timeout_cp implements Structure.ByValue {
		
	};
}
