package voice.linux.jna.asound;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : ..\voice\local\headers\\usr\include\alsa\seq_event.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class snd_seq_addr extends Structure {
	/** < Client id */
	public byte client;
	/** < Port id */
	public byte port;
	public snd_seq_addr() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("client", "port");
	}
	/**
	 * @param client < Client id<br>
	 * @param port < Port id
	 */
	public snd_seq_addr(byte client, byte port) {
		super();
		this.client = client;
		this.port = port;
	}
	public snd_seq_addr(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends snd_seq_addr implements Structure.ByReference {
		
	};
	public static class ByValue extends snd_seq_addr implements Structure.ByValue {
		
	};
}
