package voice.linux.jna.asound;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * external stored data<br>
 * <i>native declaration : ..\voice\local\headers\\usr\include\alsa\seq_event.h:257</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class snd_seq_ev_ext extends Structure {
	/** < length of data */
	public int len;
	/**
	 * < pointer to data (note: can be 64-bit)<br>
	 * C type : void*
	 */
	public Pointer ptr;
	public snd_seq_ev_ext() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("len", "ptr");
	}
	/**
	 * @param len < length of data<br>
	 * @param ptr < pointer to data (note: can be 64-bit)<br>
	 * C type : void*
	 */
	public snd_seq_ev_ext(int len, Pointer ptr) {
		super();
		this.len = len;
		this.ptr = ptr;
	}
	public snd_seq_ev_ext(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends snd_seq_ev_ext implements Structure.ByReference {
		
	};
	public static class ByValue extends snd_seq_ev_ext implements Structure.ByValue {
		
	};
}
