/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package voice.jni;

public class libnlJNI {
  public final static native long if_nametoindex(String jarg1);
  public final static native long nl_socket_alloc();
  public final static native int genl_connect(long jarg1);
  public final static native int genl_ctrl_resolve(long jarg1, String jarg2);
  public final static native long nlmsg_alloc();
  public final static native long nl_cb_alloc(int jarg1);
  public final static native long genlmsg_put(long jarg1, long jarg2, long jarg3, int jarg4, int jarg5, int jarg6, short jarg7, short jarg8);
}
