/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package voice.jni;

public interface libnlConstants {
  public final static int CTRL_CMD_UNSPEC = libnlJNI.CTRL_CMD_UNSPEC_get();
  public final static int CTRL_CMD_NEWFAMILY = libnlJNI.CTRL_CMD_NEWFAMILY_get();
  public final static int CTRL_CMD_DELFAMILY = libnlJNI.CTRL_CMD_DELFAMILY_get();
  public final static int CTRL_CMD_GETFAMILY = libnlJNI.CTRL_CMD_GETFAMILY_get();
  public final static int CTRL_CMD_NEWOPS = libnlJNI.CTRL_CMD_NEWOPS_get();
  public final static int CTRL_CMD_DELOPS = libnlJNI.CTRL_CMD_DELOPS_get();
  public final static int CTRL_CMD_GETOPS = libnlJNI.CTRL_CMD_GETOPS_get();
  public final static int CTRL_CMD_NEWMCAST_GRP = libnlJNI.CTRL_CMD_NEWMCAST_GRP_get();
  public final static int CTRL_CMD_DELMCAST_GRP = libnlJNI.CTRL_CMD_DELMCAST_GRP_get();
  public final static int CTRL_CMD_GETMCAST_GRP = libnlJNI.CTRL_CMD_GETMCAST_GRP_get();
  public final static int __CTRL_CMD_MAX = libnlJNI.__CTRL_CMD_MAX_get();

  public final static int CTRL_ATTR_UNSPEC = libnlJNI.CTRL_ATTR_UNSPEC_get();
  public final static int CTRL_ATTR_FAMILY_ID = libnlJNI.CTRL_ATTR_FAMILY_ID_get();
  public final static int CTRL_ATTR_FAMILY_NAME = libnlJNI.CTRL_ATTR_FAMILY_NAME_get();
  public final static int CTRL_ATTR_VERSION = libnlJNI.CTRL_ATTR_VERSION_get();
  public final static int CTRL_ATTR_HDRSIZE = libnlJNI.CTRL_ATTR_HDRSIZE_get();
  public final static int CTRL_ATTR_MAXATTR = libnlJNI.CTRL_ATTR_MAXATTR_get();
  public final static int CTRL_ATTR_OPS = libnlJNI.CTRL_ATTR_OPS_get();
  public final static int CTRL_ATTR_MCAST_GROUPS = libnlJNI.CTRL_ATTR_MCAST_GROUPS_get();
  public final static int __CTRL_ATTR_MAX = libnlJNI.__CTRL_ATTR_MAX_get();

}
