/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package voice.jni;

public final class nl_cb_kind {
  public final static nl_cb_kind NL_CB_DEFAULT = new nl_cb_kind("NL_CB_DEFAULT");
  public final static nl_cb_kind NL_CB_VERBOSE = new nl_cb_kind("NL_CB_VERBOSE");
  public final static nl_cb_kind NL_CB_DEBUG = new nl_cb_kind("NL_CB_DEBUG");
  public final static nl_cb_kind NL_CB_CUSTOM = new nl_cb_kind("NL_CB_CUSTOM");
  public final static nl_cb_kind __NL_CB_KIND_MAX = new nl_cb_kind("__NL_CB_KIND_MAX");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static nl_cb_kind swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + nl_cb_kind.class + " with value " + swigValue);
  }

  private nl_cb_kind(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private nl_cb_kind(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private nl_cb_kind(String swigName, nl_cb_kind swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static nl_cb_kind[] swigValues = { NL_CB_DEFAULT, NL_CB_VERBOSE, NL_CB_DEBUG, NL_CB_CUSTOM, __NL_CB_KIND_MAX };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

