/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package voice.jni;

public final class SWIGTYPE_nl_cb_kind {
  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SWIGTYPE_nl_cb_kind swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SWIGTYPE_nl_cb_kind.class + " with value " + swigValue);
  }

  private SWIGTYPE_nl_cb_kind(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SWIGTYPE_nl_cb_kind(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SWIGTYPE_nl_cb_kind(String swigName, SWIGTYPE_nl_cb_kind swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SWIGTYPE_nl_cb_kind[] swigValues = {  };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

