package voice.linux.jna.c;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * A streammarker remembers a position in a buffer.<br>
 * <i>native declaration : ..\voice\local\headers\\usr\include\libio.h:145</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _IO_marker extends Structure<_IO_marker, _IO_marker.ByValue, _IO_marker.ByReference > {
	/** C type : _IO_marker* */
	public _IO_marker.ByReference _next;
	/** C type : _IO_FILE* */
	public voice.linux.jna.c._IO_FILE.ByReference _sbuf;
	public int _pos;
	public _IO_marker() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("_next", "_sbuf", "_pos");
	}
	/**
	 * @param _next C type : _IO_marker*<br>
	 * @param _sbuf C type : _IO_FILE*
	 */
	public _IO_marker(_IO_marker.ByReference _next, voice.linux.jna.c._IO_FILE.ByReference _sbuf, int _pos) {
		super();
		this._next = _next;
		this._sbuf = _sbuf;
		this._pos = _pos;
	}
	public _IO_marker(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected _IO_marker newInstance() { return new _IO_marker(); }
	public static _IO_marker[] newArray(int arrayLength) {
		return Structure.newArray(_IO_marker.class, arrayLength);
	}
	public static class ByReference extends _IO_marker implements Structure.ByReference {
		
	};
	public static class ByValue extends _IO_marker implements Structure.ByValue {
		
	};
}
