package voice.linux.jna.c;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * Structure to use with F_GETOWN_EX and F_SETOWN_EX.<br>
 * <i>native declaration : ..\voice\local\headers\\usr\include\arm-linux-gnueabihf\bits\fcntl-linux.h:210</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class f_owner_ex extends Structure {
	/**
	 * @see __pid_type<br>
	 * Owner type of ID.<br>
	 * C type : __pid_type
	 */
	public int type;
	/**
	 * ID of owner.<br>
	 * C type : __pid_t
	 */
	public int pid;
	public f_owner_ex() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("type", "pid");
	}
	/**
	 * @param type @see __pid_type<br>
	 * Owner type of ID.<br>
	 * C type : __pid_type<br>
	 * @param pid ID of owner.<br>
	 * C type : __pid_t
	 */
	public f_owner_ex(int type, int pid) {
		super();
		this.type = type;
		this.pid = pid;
	}
	public f_owner_ex(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends f_owner_ex implements Structure.ByReference {
		
	};
	public static class ByValue extends f_owner_ex implements Structure.ByValue {
		
	};
}
