package voice.linux.jna.c;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * Length of interface name.<br>
 * <i>native declaration : net\if.h:31</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class if_nameindex extends Structure<if_nameindex, if_nameindex.ByValue, if_nameindex.ByReference > {
	/** 1, 2, ... */
	public int if_index;
	/**
	 * null terminated name: "eth0", ...<br>
	 * C type : char*
	 */
	public Pointer if_name;
	public if_nameindex() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("if_index", "if_name");
	}
	/**
	 * @param if_index 1, 2, ...<br>
	 * @param if_name null terminated name: "eth0", ...<br>
	 * C type : char*
	 */
	public if_nameindex(int if_index, Pointer if_name) {
		super();
		this.if_index = if_index;
		this.if_name = if_name;
	}
	public if_nameindex(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected if_nameindex newInstance() { return new if_nameindex(); }
	public static if_nameindex[] newArray(int arrayLength) {
		return Structure.newArray(if_nameindex.class, arrayLength);
	}
	public static class ByReference extends if_nameindex implements Structure.ByReference {
		
	};
	public static class ByValue extends if_nameindex implements Structure.ByValue {
		
	};
}
