package voice.linux.jna.c;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Length of interface name.<br>
 * <i>native declaration : net\if.h:31</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("c") 
public class if_nameindex extends StructObject {
	static {
		BridJ.register();
	}
	/** 1, 2, ... */
	@Field(0) 
	public int if_index() {
		return this.io.getIntField(this, 0);
	}
	/** 1, 2, ... */
	@Field(0) 
	public if_nameindex if_index(int if_index) {
		this.io.setIntField(this, 0, if_index);
		return this;
	}
	/**
	 * null terminated name: "eth0", ...<br>
	 * C type : char*
	 */
	@Field(1) 
	public Pointer<Byte > if_name() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * null terminated name: "eth0", ...<br>
	 * C type : char*
	 */
	@Field(1) 
	public if_nameindex if_name(Pointer<Byte > if_name) {
		this.io.setPointerField(this, 1, if_name);
		return this;
	}
	public if_nameindex() {
		super();
	}
	public if_nameindex(Pointer pointer) {
		super(pointer);
	}
}
