package voice.linux.jna.c;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * Structure used in SIOCGIFCONF request.  Used to retrieve interface<br>
 * configuration for machine (useful for programs which must know all<br>
 * networks accessible).<br>
 * <i>native declaration : net\if.h:174</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("c") 
public class ifconf extends StructObject {
	static {
		BridJ.register();
	}
	/** Size of buffer. */
	@Field(0) 
	public int ifc_len() {
		return this.io.getIntField(this, 0);
	}
	/** Size of buffer. */
	@Field(0) 
	public ifconf ifc_len(int ifc_len) {
		this.io.setIntField(this, 0, ifc_len);
		return this;
	}
	/** C type : ifc_ifcu_union */
	@Field(1) 
	public ifconf.ifc_ifcu_union ifc_ifcu() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : ifc_ifcu_union */
	@Field(1) 
	public ifconf ifc_ifcu(ifconf.ifc_ifcu_union ifc_ifcu) {
		this.io.setNativeObjectField(this, 1, ifc_ifcu);
		return this;
	}
	/** <i>native declaration : net\if.h:177</i> */
	@Union 
	public static class ifc_ifcu_union extends StructObject {
		static {
			BridJ.register();
		}
		/** C type : __caddr_t */
		@Field(0) 
		public Pointer<Byte > ifcu_buf() {
			return this.io.getPointerField(this, 0);
		}
		/** C type : __caddr_t */
		@Field(0) 
		public ifc_ifcu_union ifcu_buf(Pointer<Byte > ifcu_buf) {
			this.io.setPointerField(this, 0, ifcu_buf);
			return this;
		}
		/** C type : ifreq* */
		@Field(1) 
		public Pointer<ifreq > ifcu_req() {
			return this.io.getPointerField(this, 1);
		}
		/** C type : ifreq* */
		@Field(1) 
		public ifc_ifcu_union ifcu_req(Pointer<ifreq > ifcu_req) {
			this.io.setPointerField(this, 1, ifcu_req);
			return this;
		}
		public ifc_ifcu_union() {
			super();
		}
		public ifc_ifcu_union(Pointer pointer) {
			super(pointer);
		}
	};
	public ifconf() {
		super();
	}
	public ifconf(Pointer pointer) {
		super(pointer);
	}
}
