package voice.linux.jna.c;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
import voice.linux.jna.c.CLibrary.in_addr;
/**
 * Structure used for IP_PKTINFO.<br>
 * <i>native declaration : ..\voice\local\headers\\usr\include\arm-linux-gnueabihf\bits\in.h:127</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class in_pktinfo extends Structure<in_pktinfo, in_pktinfo.ByValue, in_pktinfo.ByReference > {
	/** Interface index */
	public int ipi_ifindex;
	/**
	 * Routing destination address<br>
	 * C type : in_addr
	 */
	public in_addr ipi_spec_dst;
	/**
	 * Header destination address<br>
	 * C type : in_addr
	 */
	public in_addr ipi_addr;
	public in_pktinfo() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ipi_ifindex", "ipi_spec_dst", "ipi_addr");
	}
	/**
	 * @param ipi_ifindex Interface index<br>
	 * @param ipi_spec_dst Routing destination address<br>
	 * C type : in_addr<br>
	 * @param ipi_addr Header destination address<br>
	 * C type : in_addr
	 */
	public in_pktinfo(int ipi_ifindex, in_addr ipi_spec_dst, in_addr ipi_addr) {
		super();
		this.ipi_ifindex = ipi_ifindex;
		this.ipi_spec_dst = ipi_spec_dst;
		this.ipi_addr = ipi_addr;
	}
	public in_pktinfo(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected in_pktinfo newInstance() { return new in_pktinfo(); }
	public static in_pktinfo[] newArray(int arrayLength) {
		return Structure.newArray(in_pktinfo.class, arrayLength);
	}
	public static class ByReference extends in_pktinfo implements Structure.ByReference {
		
	};
	public static class ByValue extends in_pktinfo implements Structure.ByValue {
		
	};
}
